### ISSUE TITLE
When dragging Email into Web Upload form the Email is moved intro trash

### ISSUE THREAD

**Issue by alexusd** [tonyfederer/OutlookFileDrag#19]
Hello!

I tried to use the plugin with some sample Code from codepen to see if it works. (https://codepen.io/Ushinro/pen/NPQzOx) Whenever i drag an email to the script the email is moved into trash in outlook. Can you reproduce the error?

best regards, alexander

**Comment by tonyfederer** [comment]
Yes, I was able to reproduce this issue.  However, I do not see this issue happen on other sites such as OneDrive.

This issue appears to happen because no dropEffect value is set, so Outlook thought you were trying to move files instead of copy them.  Adding this line to your fileDragHover event in JavaScript fixed the issue for me.

e.dataTransfer.dropEffect = 'copy';

Please try adding this line and see if this works for you.

This page has more information about the dropEffect property: https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect

**Comment by alexusd** [comment]
Hello!

Thanks for the fast answer. So it was only a bad script i was trying it with. I will keep that in mind when i start implementing it in my script. Thank you!

best regards, alexander

**Comment by Terry95P** [comment]
Hello Tony, we have just installed this without changing any code and it still puts the email into deleted items when we drag them from Outlook.
Can you please help
