### ISSUE TITLE
When dragging messages on an addin's pane, the dragEnter/dragDrop methods are not called.

### ISSUE THREAD

**Issue by TediumRemedy** [tonyfederer/OutlookFileDrag#25]
Hi Tony, 

I've hit a weird issue when trying to modify your code by adding a UI Pane to the add-in (which is a UI tab with a treeview with a couple of elements). Whenever I drag an email or an attachment onto the treeview, the treeview's DragEnter/DragDrop methods get never invoked (the only method being called is DragOver).

This problem seems to occur only if I use your DataObject substitution (this is when you create a new OutlookDataObject  data object and pass it on to NativeMethods.DoDragDrop). Whenever I pass the original dataObject to NativeMethods.DoDragDrop (with the hook enabled), all three drag'n'drop handlers start being called again.

As an experiment I tried replacing every method of the OutlookDataObject with just a call to innerObject's original implementation, but that didn't fix the issue. It feels like OutlookDataObject doesn't implement all the needed by DoDragDrop methods.

My only guess is that this can have something to do with the fact that there are actually 3 IDataObject interfaces, each of them being used in different situation:
System.Windows.Forms.IDataObject
System.Runtime.InteropServices.ComTypes.IDataObject
traditional COM IDataObject, that the OutlookFileDrag add-in are using

Do you have an idea what could be the cause of the problem?
Is there any particular reason you redefine IDataObject yourself, instead of using System.Runtime.InteropServices.ComTypes.IDataObject?

Thank you

**Comment by tonyfederer** [comment]
Without seeing your code, I don't know what is causing the issue you are experiencing.  You may want to change the logging level in the app.config file from INFO to DEBUG and then look at the log file to try to narrow down the issue.

The reason I defined the COM implementation for the IDataObject instead of using the .NET implementation is because the .NET implementation changes many of the methods from returning integers to returning voids and throws exceptions.  Since I was wrapping another COM object, it was easier to pass through the values from the inner object than convert return values to exceptions and vis versa.

**Comment by tonyfederer** [comment]
Closing issue due to no response.
