### ISSUE TITLE
Incompatible with Office Professional 

### ISSUE THREAD

**Issue by michaellanzot** [tonyfederer/OutlookFileDrag#3]
I want to use this add-in with 16.0.42.66.1001 Office Professional version but is incompatible. Tried to drag a PDF from Outlook and drop to a web browser but the icon (drag and drop symbol) disappears.

**Comment by tonyfederer** [comment]
Outlook File Drag is compatible with Office 2013 and 2016.  Please make sure to restart Outlook once you run the installer.  Also, please check that he add-in is enabled by going to File > Options, then clicking "Add-ins" on the left, then clicking the "Go..." button at the bottom.  Make sure OutlookFileDrag is checked and click OK.

If you are still having issues, please post the log file located at C:\Users\_username_\AppData\Roaming\OutlookFileDrag.

Also, please let me know what browser you are using.

**Comment by michaellanzot** [comment]
Hi. Thank you very much. 

1. Outlook was restarted after add-in was installed but continues with the same issue. 
2. The add-in is enabled in Outlook. 
3. Tested with Chrome 65.0.3325.181 and Firefox 59.0.2.
4. Tested on another computer with the same Office version (Professional Plus 64bit 16.0.42.66.1001) but the same issue


OutlookFileDrag Log:

https://multinationalpr-my.sharepoint.com/:f:/p/michael_lanzot/EmmfTaE53WBIjy2PF9smClgBHTibbWhksGkWW-sSNWmPfw?e=fUKc8A

**Comment by djoulz22** [comment]
Same issue for me
Outlook 2013
Firefox/Chrome/IE11
No Drag (Attachment and Mail) possible!

**Comment by evoaaron** [comment]
Hi all, 

You got:
System.OverflowException: Arithmetic operation resulted in an overflow.

Am I right in thinking your mouse pointer doesn't change when dragging like it would without the add-in?

The pointer value may have exceeded the size int can hold. Perhaps could be resolved if you change the variable to use an Int64?

**Comment by michaellanzot** [comment]
Tested with Office 365 Business 16.0.9126.2116 on the same computer and it works like a charm. But I want to use it with 16.0.42.66.1001 because it's our company's version.

Otherwise:
Q: "Am I right in thinking your mouse pointer doesn't change when dragging like it would without the add-in?"

A: The mouse pointer doesn't change when try to drag with the add-in and for example drag and drop to a folder or somewhere else works fine without the add-in.

Q; "The pointer value may have exceeded the size int can hold. Perhaps could be resolved if you change the variable to use an Int64?"

A: Please explain little more

**Comment by evoaaron** [comment]
The mouse pointer doesn't change because it is hitting an exception on the drag event, in this case the overflow I specified previously. 

Inside the DataObjectHelper class it is using int32, for the IntPtr's - modify these to Int64's. 

**Change the following to:**
Line 55:
IntPtr ptrFiles = new IntPtr(ptrDropFiles.ToInt64() + Marshal.SizeOf(dropFiles));

Line 190:
IntPtr fdPtr = (IntPtr)((Int64)fgdaPtr + Marshal.SizeOf(fgdaPtr));

Line 203:
fdPtr = (IntPtr)((Int64)fdPtr + Marshal.SizeOf(fd));

Just re-downloaded the source, tested and I had the same problem. I then made these amendments and is now working for myself.

**Comment by michaellanzot** [comment]
Thank you! The issue has been resolved

**Comment by tonyfederer** [comment]
I fixed the pointers to work for both 32-bit and 64-bit by using the IntPtr.Add static function.  This method is cleaner anyway because it doesn't have to convert the pointers to integers and back to pointers.  I also fixed an issue where the first 2 characters were being cut off the filename of the dragged message.  These 64-bit fixed have been published in version 1.0.1.
