### ISSUE TITLE
Drag calendar entry causes Outlook to fall

### ISSUE THREAD

**Issue by George-Developer-1** [tonyfederer/OutlookFileDrag#5]
Hello,
with Outlook 32 bit proffesional on Win 10/64 bit - when I try to drag any entry in calendar, it causes Outlook to fall and restart completly. See picture, trying to move yellow meeting to other day (Outlook window is in Czech)

![image](https://user-images.githubusercontent.com/33361911/41122942-65be76d2-6a9d-11e8-99ec-194733536be5.png)

**Comment by wout-de-jong** [comment]
Hi, just to unconfirm. I do NOT have this issue using 32 bit Outlook 2013 on Win 10 (64 bit).

**Comment by tonyfederer** [comment]
Yes, this is known issue.  I have not been able to figure out yet why this happens.

**Comment by tonyfederer** [comment]
This issue has been fixed in version 1.0.5.  Please install the latest version.

[Download for 64-bit Windows (Outlook 32-bit or 64-bit)](https://github.com/tonyfederer/OutlookFileDrag/files/2674450/OutlookFileDragSetup_x64.zip)
[Download for 32-bit Windows](https://github.com/tonyfederer/OutlookFileDrag/files/2674451/OutlookFileDragSetup.zip)
